logging:
  level:
    com.sikugeon.damda: debug
    org.springframework.web: debug
    org.springframework.test: debug

spring.servlet.multipart.maxFileSize: 50MB
spring.servlet.multipart.maxRequestSize: 50MB

server:
  error:
    include-message: always
  port: 5000